app/chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"

urlpatterns = [
    path("", views.home, name="home"),
    path("bot-response/", views.bot_response, name="bot_response"),
]

app/djangochatbot/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("chat.urls")),
]

app/chat/models.py
from django.db import models

# Create your models here.

app/chat/forms.py
from django import forms


class ChatMessageForm(forms.Form):
    message = forms.CharField(required=True, max_length=100)

app/chat/views.py
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
from django.http import HttpResponse
from django.shortcuts import render

from .forms import ChatMessageForm

chatbot = ChatBot(**settings.CHATTERBOT)


def home(request):
    form = ChatMessageForm()
    context = {"form": form}
    return render(request, "chat/home.html", context)


def bot_response(request):
    if request.method == "POST":
        form = ChatMessageForm(request.POST)
        if form.is_valid():
            input_message = form.data["message"]
            response_message = chatbot.get_response(input_message)
            http_response = HttpResponse()
            http_response.write(response_message)
            return http_response

app/templates/chat/home.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Chatbot app</title>
    <style>
      .log-window {
        max-width: 500px;
        max-height: 300px;
        overflow-y: scroll;
      }
    </style>
  </head>
  <body>
    <h1>Talk with chatbot</h1>
    <div id="chat-log" class="log-window"></div>

    <form method="POST" action="{% url 'chat:bot_response' %}">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Send</button>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
      const chatLog = $("#chat-log");

      function createRow(text) {
        const row = $("<p></p>");
        row.text(text);
        chatLog.append(row);
      }

      $("form").submit(function (event) {
        event.preventDefault();
        const form = $(this);

        $.ajax({
          url: form.prop("action"),
          type: form.prop("method"),
          data: form.serialize(),
          dataType: "text",
        })
          .done(function (statement) {
            const input = $("#id_message");
            createRow("You -> " + input.val());
            createRow("bot: " + statement);
            input.val("");
            chatLog[0].scrollTop = chatLog[0].scrollHeight;
          })
          .fail(function () {
            window.alert("もう一度やり直してください");
          });
      });
    </script>
  </body>
</html>